server:
   port: 8082
spring:
	datasource:
		url: jdbc:mysql://localhost:3306/sakila
		username: root
		password: P@ssw0rd
		driver-class: com.mysql.jdbc.Driver
    jpa:
		show-sql: true
		hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
		properties.hibernate.id.new_generator_mappings: false
   main:
		allow-bean-definition-overriding: true


spring:
  profiles:
    active: local
---
spring: 
   profiles: dev 
   apiprops:
      url :http://devenv/emp/	
  
  
---
spring:
   profiles: local
   apiprops: 
      url :http://localhost:8081/emp/	
 
      

      
      
      
